// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BillForm: typeof import('./src/components/BillForm/BillForm.vue')['default']
    CompanyFields: typeof import('./src/components/CompanyFields/CompanyFields.vue')['default']
    Invoice: typeof import('./src/components/Invoice/Invoice.vue')['default']
    SellerFields: typeof import('./src/components/SellerFields/SellerFields.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export { }
